fix concurrency bug
When using two strategies simultaneously you may encounter the following errors:

- NoMethodError: undefined method `fetch' for 1:Integer

```
/usr/local/bundle/gems/prop-2.2.4/lib/prop/leaky_bucket_strategy.rb:40:in
 `compare_threshold?'
/usr/local/bundle/gems/prop-2.2.4/lib/prop/limiter.rb:153:in `_throttle'
/usr/local/bundle/gems/prop-2.2.4/lib/prop/limiter.rb:91:in `throttle!'
```

- TypeError: no implicit conversion of Integer into Hash

```
/usr/local/bundle/gems/prop-2.2.4/lib/prop/interval_strategy.rb:33:in
 `>'
/usr/local/bundle/gems/prop-2.2.4/lib/prop/interval_strategy.rb:33:in
 `compare_threshold?'
/usr/local/bundle/gems/prop-2.2.4/lib/prop/limiter.rb:153:in `_throttle'
/usr/local/bundle/gems/prop-2.2.4/lib/prop/limiter.rb:91:in `throttle!'
```

Those errors happen because [`Prop ::LeakyBucketStrategy.compare_threshold?(counter, operator, options)`](https://github.com/zendesk/prop/blob/db90750ceb53aedf7df9a7cb2ea473c7832e1ccc/lib/prop/leaky_bucket_strategy.rb#L39-L41) sometimes gets an `Integer` as a `counter` and [`Prop::IntervalStrategy.compare_threshold?(counter, operator, options)`](https://github.com/zendesk/prop/blob/db90750ceb53aedf7df9a7cb2ea473c7832e1ccc/lib/prop/interval_strategy.rb#L31-L34) sometimes gets a `Hash` as a `counter`, but it should be vice versa. The reason is a class instance variable [`@strategy`](https://github.com/zendesk/prop/blob/db90750ceb53aedf7df9a7cb2ea473c7832e1ccc/lib/prop/limiter.rb#L180) is reassigned by different threads in the same process. Particularly around [this line](https://github.com/zendesk/prop/blob/db90750ceb53aedf7df9a7cb2ea473c7832e1ccc/lib/prop/limiter.rb#L152) because of cache latency I suppose.

The bug was [commited](https://github.com/zendesk/prop/commit/730d89936353db7f2c98697d56d6e0e95e49def9) as a part of [a big PR](https://github.com/zendesk/prop/pull/6), so no surprise nobody thought about this case.